[tool.poetry]
name = "1001-albums-push"
version = "0.1.0"
description = ""
authors = ["Francis Conroy <francis.conroy@switchdin.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
